export const COMPANY_CREATE_FORM_FIELDS = new Map([
  ['company_name', { type: 'text', name: 'company_name', label: 'Company Name' }],
  ['identity_type', { type: 'dropdown', name: 'identity_type', label: 'Identity Type' }],
  ['identity_number', { type: 'text', name: 'identity_number', label: 'Identity Number' }],
  ['currency', { type: 'dropdown', name: 'currency', label: 'Currency' }],
  ['company_photo', { type: 'image', name: 'company_photo', label: 'Company Photo' }],
  ['active', { type: 'toggle', name: 'active', label: 'Active' }],
  ['address_1', { type: 'text', name: 'address_1', label: 'Address Line 1' }],
  ['address_2', { type: 'text', name: 'address_2', label: 'Address Line 2' }],
  ['country', { type: 'dropdown', name: 'country', label: 'Country' }],
  ['phone_number', { type: 'number', name: 'phone_number', label: 'Phone Number' }],
  ['mobile_number', { type: 'number', name: 'mobile_number', label: 'Mobile Number' }],
  ['website', { type: 'text', name: 'website', label: 'Website URL' }],
  ['img_url', { type: 'text', name: 'img_url', label: 'Image URL' }],
]);
