export const EMPLOYEE_REQUEST_FIELD_MAP = new Map([
  ['username', { type: 'text', name: 'username', label: 'Username' }],
  ['email', { type: 'email', name: 'email', label: 'Email' }],
  ['password', { type: 'password', name: 'password', label: 'Password' }],
  ['commencement_date', { type: 'date', name: 'commencement_date', label: 'Commencement Date' }],
  ['first_name', { type: 'text', name: 'first_name', label: 'First Name' }],
  ['middle_name', { type: 'text', name: 'middle_name', label: 'Middle Name' }],
  ['last_name', { type: 'text', name: 'last_name', label: 'Last Name' }],
  ['preferred_name', { type: 'text', name: 'preferred_name', label: 'Preferred Name' }],
  ['phone_number', { type: 'number', name: 'phone_number', label: 'Phone Number' }],
  ['mobile_number', { type: 'number', name: 'mobile_number', label: 'Mobile Number' }],
  ['address_1', { type: 'text', name: 'address_1', label: 'Address Line 1' }],
  ['address_2', { type: 'text', name: 'address_2', label: 'Address Line 2' }],
  ['address_3', { type: 'text', name: 'address_3', label: 'Address Line 3' }],
  ['address_4', { type: 'text', name: 'address_4', label: 'Address Line 4' }],
  ['city', { type: 'text', name: 'city', label: 'City' }],
  ['state', { type: 'text', name: 'state', label: 'State' }],
  ['postal_code', { type: 'number', name: 'postal_code', label: 'Postal Code' }],
  ['country', { type: 'dropdown', name: 'country', label: 'Country' }],
  ['gender', { type: 'dropdown', name: 'gender', label: 'Gender' }],
  ['race', { type: 'dropdown', name: 'race', label: 'Race' }],
  ['ethnic_name', { type: 'text', name: 'ethnic_name', label: 'Ethnic Name' }],
  ['date_of_birth', { type: 'date', name: 'date_of_birth', label: 'Date Of Birth' }],
  ['identity_type', { type: 'dropdown', name: 'identity_type', label: 'Identity Type' }],
  ['identity_number', { type: 'text', name: 'identity_number', label: 'Identity No.' }],
  ['nationality', { type: 'dropdown', name: 'nationality', label: 'Nationality' }],
  ['residency_status', { type: 'dropdown', name: 'residency_status', label: 'Residency Status' }],
  ['pr_conversion_date', { type: 'date', name: 'pr_conversion_date', label: 'PR Conversion Date' }],
  ['emergency_name', { type: 'text', name: 'emergency_name', label: 'Emergency Name' }],
  ['emergency_relationship', { type: 'text', name: 'emergency_relationship', label: 'Emergency Relationship' }],
  ['emergency_address_1', { type: 'text', name: 'emergency_address_1', label: 'Emergency Address Line 1' }],
  ['emergency_address_2', { type: 'text', name: 'emergency_address_2', label: 'Emergency Address Line 2' }],
  ['emergency_address_3', { type: 'text', name: 'emergency_address_3', label: 'Emergency Address Line 3' }],
  ['emergency_address_4', { type: 'text', name: 'emergency_address_4', label: 'Emergency Address Line 4' }],
  ['emergency_contact_number', { type: 'number', name: 'emergency_contact_number', label: 'Emergency Contact Number' }],
  ['bank_name', { type: 'text', name: 'bank_name', label: 'Bank Name' }],
  ['bank_account_number', { type: 'text', name: 'bank_account_number', label: 'Bank Account Number' }],
  ['remarks', { type: 'textarea', name: 'remarks', label: 'Remarks' }],
]);
