export const EMPLOYEE_REQUEST_FIELD_MAP = new Map([
  ['username', { type: 'text', name: 'username', label: 'Username', disabled: false, data: null }],
  ['email', { type: 'email', name: 'email', label: 'Email', disabled: false, data: null }],
  ['password', { type: 'password', name: 'password', label: 'Password', disabled: false, data: null }],
  [
    'commencement_date',
    { type: 'date', name: 'commencement_date', label: 'Commencement Date', disabled: false, data: null },
  ],
  ['first_name', { type: 'text', name: 'first_name', label: 'First Name', disabled: false, data: null }],
  ['middle_name', { type: 'text', name: 'middle_name', label: 'Middle Name', disabled: false, data: null }],
  ['last_name', { type: 'text', name: 'last_name', label: 'Last Name', disabled: false, data: null }],
  ['preferred_name', { type: 'text', name: 'preferred_name', label: 'Preferred Name', disabled: false, data: null }],
  ['nric', { type: 'text', name: 'nric', label: 'NRIC', disabled: false, data: null }],
  ['phone_number', { type: 'text', name: 'phone_number', label: 'Phone Number', disabled: false, data: null }],
  ['mobile_number', { type: 'text', name: 'mobile_number', label: 'Mobile Number', disabled: false, data: null }],
  ['address_1', { type: 'text', name: 'address_1', label: 'Address Line 1', disabled: false, data: null }],
  ['address_2', { type: 'text', name: 'address_2', label: 'Address Line 2', disabled: false, data: null }],
  ['address_3', { type: 'text', name: 'address_3', label: 'Address Line 3', disabled: false, data: null }],
  ['address_4', { type: 'text', name: 'address_4', label: 'Address Line 4', disabled: false, data: null }],
  ['city', { type: 'text', name: 'city', label: 'City', disabled: false, data: null }],
  ['state', { type: 'text', name: 'state', label: 'State', disabled: false, data: null }],
  ['postal_code', { type: 'number', name: 'postal_code', label: 'Postal Code', disabled: false, data: null }],
  ['country', { type: 'dropdown', name: 'country', label: 'Country', disabled: false, data: null }],
  ['gender', { type: 'dropdown', name: 'gender', label: 'Gender', disabled: false, data: null }],
  ['race', { type: 'dropdown', name: 'race', label: 'Race', disabled: false, data: null }],
  ['ethnic_name', { type: 'text', name: 'ethnic_name', label: 'Ethnic Name', disabled: false, data: null }],
  ['date_of_birth', { type: 'date', name: 'date_of_birth', label: 'Date Of Birth', disabled: false, data: null }],
  ['nationality', { type: 'dropdown', name: 'nationality', label: 'Nationality', disabled: false, data: null }],
  [
    'residency_status',
    { type: 'dropdown', name: 'residency_status', label: 'Residency Status', disabled: false, data: null },
  ],
  [
    'pr_conversion_date',
    { type: 'date', name: 'pr_conversion_date', label: 'PR Conversion Date', disabled: false, data: null },
  ],
  ['emergency_name', { type: 'text', name: 'emergency_name', label: 'Emergency Name', disabled: false, data: null }],
  [
    'emergency_relationship',
    { type: 'text', name: 'emergency_relationship', label: 'Emergency Relationship', disabled: false, data: null },
  ],
  [
    'emergency_address_1',
    { type: 'text', name: 'emergency_address_1', label: 'Emergency Address Line 1', disabled: false, data: null },
  ],
  [
    'emergency_address_2',
    { type: 'text', name: 'emergency_address_2', label: 'Emergency Address Line 2', disabled: false, data: null },
  ],
  [
    'emergency_address_3',
    { type: 'text', name: 'emergency_address_3', label: 'Emergency Address Line 3', disabled: false, data: null },
  ],
  [
    'emergency_address_4',
    { type: 'text', name: 'emergency_address_4', label: 'Emergency Address Line 4', disabled: false, data: null },
  ],
  [
    'emergency_contact_number',
    { type: 'text', name: 'emergency_contact_number', label: 'Emergency Contact Number', disabled: false, data: null },
  ],
  ['bank_name', { type: 'text', name: 'bank_name', label: 'Bank Name', disabled: false, data: null }],
  [
    'bank_account_number',
    { type: 'text', name: 'bank_account_number', label: 'Bank Account Number', disabled: false, data: null },
  ],
  ['remarks', { type: 'textarea', name: 'remarks', label: 'Remarks', disabled: false, data: null }],
]);
