export const EMPLOYEE_REQUEST_FIELD_MAP = new Map([
  ['username', 'Username'],
  ['email', 'Email'],
  ['password', 'Password'],
  ['commencement_date', 'Commencement Date'],
  ['first_name', 'First Name'],
  ['middle_name', 'Middle Name'],
  ['last_name', 'Last Name'],
  ['preferred_name', 'Preferred Name'],
  ['nric', 'NRIC'],
  ['phone_number', 'Phone Number'],
  ['mobile_number', 'Mobile Number'],
  ['address_1', 'Address Line 1'],
  ['address_2', 'Address Line 2'],
  ['address_3', 'Address Line 3'],
  ['address_4', 'Address Line 4'],
  ['city', 'City'],
  ['state', 'State'],
  ['postal_code', 'Postal Code'],
  ['country', 'Country'],
  ['gender', 'Gender'],
  ['race', 'Race'],
  ['ethnic_name', 'Ethnic Name'],
  ['date_of_birth', 'Date Of Birth'],
  ['nationality', 'Nationality'],
  ['residency_status', 'Residency Status'],
  ['pr_conversion_date', 'PR Conversion Date'],
  ['emergency_name', 'Emergency Name'],
  ['emergency_relationship', 'Emergency Relationship'],
  ['emergency_address_1', 'Emergency Address Line 1'],
  ['emergency_address_2', 'Emergency Address Line 2'],
  ['emergency_address_3', 'Emergency Address Line 3'],
  ['emergency_address_4', 'Emergency Address Line 4'],
  ['emergency_contact_number', 'Emergency Contact Number'],
  ['bank_name', 'Bank Name'],
  ['bank_account_number', 'Bank Account Number'],
  ['remarks', 'Remarks'],
]);
